Models/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using DocumentProcessing.Abstraction;
using Microsoft.AspNetCore.Identity;

namespace DocumentProcessing.Models
{
    public class Document : IDocumentModel
    {
        [Key]
        public Guid Id { get; set; }

        public DateTime Date { get; set; } = DateTime.Now;
        
        public long EntryNumber { get; set; }

        public string AppointmentNumber { get; set; }
        
        public Guid? ApplicantId { get; set; }
        
        public Guid? StatusId { get; set; }

        public Guid? VisaTypeId { get; set; }

        public Guid? VisaDateTypeId { get; set; }

        public Guid? PurposeId { get; set; }
        
        public Guid OwnerId { get; set; }
        
        public string RecipientId { get; set; }

        public string Description { set; get; }

        public string VisaDate { get; set; }

        public virtual ApplicationUser Recipient { get; set; }
        
        [ForeignKey("ApplicantId")]
        public virtual Applicant Applicant { get; set; }
        
        [ForeignKey("OwnerId")]
        public virtual DocumentOwner Owner { get; set; }
        
        [ForeignKey("PurposeId")]
        public virtual Purpose Purpose { get; set; }
        
        [ForeignKey("StatusId")]
        public virtual Status Status { get; set; }

        [ForeignKey("VisaTypeId")]
        public virtual VisaType VisaType { get; set; }

        [ForeignKey("VisaDateTypeId")]
        public virtual VisaDateType VisaDateType { get; set; }

        public Appointment Appointment { get; set; }

        public virtual IEnumerable<ScannedFile> ScannedFiles { get; set; }

        public virtual IEnumerable<RequestId> RequestId { get; set; }

        public string VisaId { get; set; }
    }
}

ViewModels/DocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using DocumentProcessing.Abstraction;
using Microsoft.AspNetCore.Http;

namespace DocumentProcessing.ViewModels
{
    public class DocumentViewModel : IDocumentModel, IValidatableObject
    {
        public Guid Id { get; set; }

        public string RecipientId { get; set; }

        public ApplicantType ApplicantType { get; set; }

        public PurposeType PurposeType { get; set; }

        [DisplayName("Макони вуруди ҳуҷҷат")]
        [Required(ErrorMessage = "Макони вуруди ҳуҷҷат холи аст!")]
        public Guid OwnerId { get; set; }

        [DisplayName("Номи ташкилот")]
        public string ApplicantName { get; set; }

        [DisplayName("Мақсади муроҷиат")]
        public string PurposeName { get; set; }

        [DisplayName("Номи ташкилот")]
        public Guid? ApplicantId { get; set; }

        public string EntryNumber { get; set; }

        [DisplayName("Мақсади муроҷиат")]

        public Guid? PurposeId { get; set; }

        [DisplayName("Ҳолати ҳуҷҷат")]

        public Guid? StatusId { get; set; }
        
        [DisplayName("то")]
    
        [StringLength(2, MinimumLength = 1, ErrorMessage = "Хадди нихоии раками ичозатшуда барои Рӯз то 30 ва барои Мох то 32")]
        public string VisaDate { get; set; }

        [DisplayName("Навъи раводид")]
       
        public Guid? VisaTypeId { get; set; }

        [DisplayName("Мӯҳлати раводид")]
        
        public Guid? VisaDateTypeId { get; set; }

        [DisplayName("Эзоҳ")]
        public string Description { get; set; }

        public AppointmentViewModel Appointment { get; set; }

        public RequestIdViewMModel RequestId { get; set; }

        [DisplayName("Иловаи ҳуҷҷати сканшуда")]
        [Required(ErrorMessage = "Иловаи ҳуҷҷати сканшуда холи аст!")]
        public List<ScannedFileViewModel> ScannedFiles { get; set; } = new List<ScannedFileViewModel>();

        [DisplayName("ID-и дархост")]
        
        public string VisaId { get; set; }
        
        
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (PurposeId == null && string.IsNullOrEmpty(PurposeName))
            {
                yield return new ValidationResult("Номи ташкилот холи аст!", new []{ "PurposeName" });
            }
            
            if (ApplicantId == null && string.IsNullOrEmpty(ApplicantName))
            {
                yield return new ValidationResult("Номи ташкилот холи аст!", new []{ "ApplicantName" });
            }
        }
    }
}

ViewModels/PrintViewModel.cs
namespace DocumentProcessing.ViewModels
{
    public class PrintViewModel
    {
        public string AppointmentNumber { get; set; }

        public string Owner { get; set; }

        public string Applicant { get; set; }

        public string Purpose { get; set; }

        public string Recipient { get; set; }

        public string VisaId { get; set; }

        public string VisaType { get; set; }

        public string VisaDateType { get; set; }

        public string VisaDate { get; set; }

        public string Base64Stamp { get; set; }
    }
}

Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using AutoMapper;
using DocumentProcessing.Abstraction;
using DocumentProcessing.Data;
using DocumentProcessing.Helpers;
using DocumentProcessing.Models;
using DocumentProcessing.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;

namespace DocumentProcessing.Controllers
{
    [Authorize]
    public class DocumentsController : Controller
    {
        public string VisaID = "";
        private const int PageSize = 10;

        private readonly IFileUploader _fileUploader;
        private readonly IElectronicStamp _electronicStamp;
        private readonly ILogger<DocumentsController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public DocumentsController(
            IFileUploader fileUploader,
            IElectronicStamp electronicStamp,
            ILogger<DocumentsController> logger,
            ApplicationDbContext context,
            IMapper mapper)
        {
            _fileUploader = fileUploader;
            _electronicStamp = electronicStamp;
            _logger = logger;
            _context = context;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index(
            [FromQuery(Name = "q")] string searchText,
            [FromQuery(Name = "dateFrom")] string startDate,
            [FromQuery(Name = "dateFor")] string endDate,
            int? pageNumber)
        {
            var documents = _context.Documents.OrderByDescending(x => x.Date)
                .Include(x => x.Applicant)
                .Include(x => x.Purpose)
                .Include(x => x.Status)
                .Include(x => x.VisaType)
                .Include(x => x.VisaDateType)
                .Include(x => x.ScannedFiles)
                .Include(x => x.Owner)
                .Include(x => x.Recipient)
                .Include(x => x.Appointment).AsQueryable();
            
            if (!string.IsNullOrEmpty(endDate) && !string.IsNullOrEmpty(startDate))
            {
                var parsedStartDate = DateTime.ParseExact(startDate, "dd.MM.yyyy", CultureInfo.InvariantCulture);
                var parsedEndDate = DateTime.ParseExact(endDate, "dd.MM.yyyy", CultureInfo.CurrentCulture);

                ViewBag.DateFor = endDate;
                ViewBag.DateFrom = startDate;
                documents = documents.Where(x => x.Date >= parsedStartDate && x.Date < parsedEndDate);
            }

            if (!string.IsNullOrEmpty(searchText))
            {
                ViewBag.SearchText = searchText;
                documents = documents.Where(Search(searchText));
            }

            _logger.LogInformation(documents.ToSql());

            var list = await MappedPaginatedList<DocumentListViewModel>
                .CreateAsync(documents, _mapper, pageNumber ?? 1, PageSize);

            return View(list);
        }

        private Expression<Func<Document, bool>> Search(string searchText)
        {
            var patternMatch = $"%{searchText}%";
            return x => EF.Functions.ILike(x.Applicant.Name, patternMatch)
                        || EF.Functions.ILike(x.Owner.Name, patternMatch)
                        || EF.Functions.ILike(x.EntryNumber.ToString(), patternMatch)
                        || EF.Functions.ILike(x.Recipient.Name, patternMatch)
                        || EF.Functions.ILike(x.Purpose.Name, patternMatch)
                        || EF.Functions.ILike(x.Status.Name, patternMatch)
                        || EF.Functions.ILike(x.VisaType.Name, patternMatch)
                        || EF.Functions.ILike(x.VisaDateType.Name, patternMatch);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var selectedOwner = await _context.DocumentOwners
                .OrderBy(x => x.Name)
                .FirstOrDefaultAsync();

            PopulateOwnersDropDownList(selectedOwner);
            PopulateApplicantsDropDownList();
            PopulateStatusesDropDownList();
            PopulateVisaTypeDropDownList();
            PopulateVisaDateTypeDropDownList();
            PopulatePurposesDropDownList();

            return View(new DocumentViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(DocumentViewModel viewModel, IList<IFormFile> files, IFormCollection ifc)
        {
            string test = ifc["VisaId"];
            VisaID = test;
            if (ModelState.IsValid)
            {
                await CreateApplicantIfNotExist(viewModel);
                await CreatePurposeIfNotExist(viewModel);
                var document = _mapper.Map<Document>(viewModel);
                try
                {
                    document.VisaId = VisaID;
                    string[] strArr = null;
                    RequestId req = new RequestId();
                    char[] splitchar = { ',' };
                    if (String.IsNullOrEmpty(VisaID)) {  } else { strArr = VisaID.Split(splitchar); }

                
                  
                    await _context.AddAsync(document);
                    await _context.SaveChangesAsync();
                    
                    if (files.Any())
                    {
                        var newFiles = await _fileUploader.GetScannedFilesForDocument(document, files);
                        await _context.ScannedFiles.AddRangeAsync(newFiles);
                        await _context.SaveChangesAsync();
                    }
                    if (String.IsNullOrEmpty(VisaID)) { }
                    else
                    {
                        foreach (var id in strArr)
                        {

                            req.Number = id;
                            req.DocumentId = document.Id;
                            req.Id = Guid.NewGuid();

                            await _context.AddAsync(req);
                            await _context.SaveChangesAsync();
                        }
                    }

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex) when (ex.GetType() == typeof(DbUpdateException))
                {
                    ModelState.AddModelError("", "Unable to save changes. " +
                                                 "Try again, and if the problem persists, " +
                                                 "see your system administrator.");
                }
            }

            SetSelectedDropDownLists(viewModel);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Progress()
        {
            var progressResult = HttpContext.Session.GetInt32("progress").ToString();
            return Content(progressResult);
        }

        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = _context.Documents
                .Include(x => x.ScannedFiles)
                .Include(x => x.Appointment)
                .FirstOrDefault(x => x.Id == id);

            var request_Id = _context.RequestId.AsQueryable();
            request_Id = request_Id.Where(x => x.DocumentId == document.Id);
            var request_Id_Count = request_Id.Count();
            ViewBag.reg = request_Id;
            ViewBag.reqCount = request_Id_Count;
            
            if (document == null)
            {
                return NotFound();
            }

            var viewModel = _mapper.Map<DocumentViewModel>(document);
            viewModel.ApplicantType = ApplicantType.Existing;
            viewModel.PurposeType = PurposeType.Existing;

            SetSelectedDropDownLists(document);

            return View(viewModel);
        }

        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPost(DocumentViewModel viewModel, IList<IFormFile> files, IFormCollection ifc)
        {
            string test = ifc["VisaId"];
            string[] strArr = null;
            RequestId req = new RequestId();
            char[] splitchar = { ',' };

            VisaID = test;
            if (String.IsNullOrEmpty(VisaID)) { } else { strArr = VisaID.Split(splitchar); }

            if (ModelState.IsValid)
            {
                var originalDocument = _context.Documents
                    .Include(x => x.Appointment)
                    .AsNoTracking()
                    .FirstOrDefault(x => x.Id == viewModel.Id);

                if (originalDocument == null)
                {
                    return NotFound();
                }

                await CreateApplicantIfNotExist(viewModel);
                await CreatePurposeIfNotExist(viewModel);
                var document = _mapper.Map<Document>(viewModel);
                document.Date = originalDocument.Date;

                var request_Id = _context.RequestId.AsQueryable();
                request_Id = request_Id.Where(x => x.DocumentId == document.Id);
                var request_Id_Count = request_Id.Count();
                ViewBag.reg = request_Id;
                ViewBag.reqCount = request_Id_Count;
                var hasAddedFiles = files.Any();
                var hasRequestIdChanges = false;
                var hasDocumentChanges = HasChangesBetweenTwoDocuments(originalDocument, document);
                var hasRemovedFiles = viewModel.ScannedFiles.Any(x => x.IsDeleted);
                bool hasError = false;

              

                try

Views/Documents/Delete.cshtml
@model DocumentProcessing.ViewModels.DocumentListViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Нобуд кардан</h1>
<hr>
<div class="container">
    <h3 style="text-align: center;">Мутмаин ҳастед, ки мехоҳед ин ҳуҷҷатро нобуд созед?</h3>
    <div class="card col-md-12">
        <br>
        <h4>Ҳуҷҷат</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Applicant)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Applicant)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Purpose)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Purpose)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Recipient)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Recipient)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Status)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Status)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Appointment)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Appointment)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.EntryNumber)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.EntryNumber)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.VisaId)
            </dt>
            <dd class="col-sm-8">
                @ViewBag.ReqId
            </dd>

            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.VisaDateType)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.VisaDate)   @Html.DisplayFor(model => model.VisaDateType)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.VisaType)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.VisaType)
            </dd>

            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Нобуд кардан" class="btn btn-danger" /> |
            <a asp-action="Index" class="btn btn-default">Бекор</a>
        </form>
    </div>
</div>

Views/Documents/Index.cshtml
@using Microsoft.AspNetCore.Identity

@model MappedPaginatedList<DocumentListViewModel>
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Ҳуҷҷатҳо";
}

@{
    var user = await UserManager.GetUserAsync(User);
    var admin = await UserManager.IsInRoleAsync(user, "Admin");
    var manager = await UserManager.IsInRoleAsync(user, "Manager");
    bool isAdminOrManager = admin || manager;
    int i = 1;
}
<!-- Table with panel -->
<div class="card card-cascade narrower">

    <!--Card image-->
    <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
        <div class="">
            <a asp-action="Create" class="btn btn-labeled btn-primary">
                <span class="btn-label">
                    <i class="fa fa-plus"></i>
                </span> Илова намудан
            </a>
        </div>
        
        <div class="col-md-3">
            <form asp-controller="Documents" asp-action="Index" method="get">
                <div class="input-group">
                    <input placeholder="Аз санаи:" data-provide="datepicker" class="form-control" id="dateFrom" name="dateFrom" value="@ViewBag.DateFrom" />
                    <input placeholder="То санаи:" class="form-control" data-provide="datepicker" id="dateFor" name="dateFor" value="@ViewBag.DateFor" />
                    <div class="input-group-append">
                        <button class="btn btn-secondary" type="submit">
                            <i class="fa fa-calendar-check"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-2">
            <form asp-controller="Documents" asp-action="Index" method="get">
                <div class="input-group">
                    <input type="text" class="form-control" name="q" value="@ViewBag.SearchText" placeholder="Ҷустуҷу...">
                    <div class="input-group-append">
                        <button class="btn btn-secondary" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>


        </div>

    </div>
    <!--/Card image-->

    <div class="px-4">

        <div class="table-wrapper">
            <!--Table-->
            <table id="Экспорт" class="table table-hover mb-0">

                <!--Table head-->
                <thead>
                    <tr>
                        <th>
                            <label class="form-check-label mr-2 label-table" for="checkbox">№</label>
                        </th>
                        <th class="th-lg" style="width: 500px;">
                            @Html.DisplayNameFor(model => model.ItemType.Applicant)
                        </th>
                        <th class="th-lg">
                            @Html.DisplayNameFor(model => model.ItemType.Date)
                        </th>
                        <th class="th-lg">
                            @Html.DisplayNameFor(model => model.ItemType.EntryNumber)
                        </th>
                        <th class="th-lg">
                            @Html.DisplayNameFor(model => model.ItemType.Purpose)
                        </th>
                        <th class="th-lg todelete">
                            @Html.DisplayNameFor(model => model.ItemType.Appointment)
                        </th>
                        <th class="th-lg todelete">
                            @Html.DisplayNameFor(model => model.ItemType.Status)
                        </th>
                        <th class="th-lg">
                            @Html.DisplayNameFor(model => model.ItemType.Recipient)
                        </th>
                        <th class="th-lg todelete">
                            @Html.DisplayNameFor(model => model.FirstOrDefault().ScannedDocuments)
                        </th>
                        <th class="th-lg todelete">
                            Тағйир додан
                        </th>

                    </tr>
                </thead>
                <!--Table head-->
                <!--Table body-->
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            @{
                                var rowNo = (Model.PageIndex - 1) * 10 + i;
                                i++;
                            }
                            <td>
                                @rowNo
                            </td>
                            <td style="width: 400px;">
                                @Html.DisplayFor(modelItem => item.Applicant)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EntryNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Purpose)
                            </td>
                            <td class="todelete">
                                @Html.DisplayFor(modelItem => item.Appointment)
                            </td>

                            <td class="todelete">
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Recipient)
                            </td>

                            <td class="todelete">
                                @foreach (var doc in item.ScannedDocuments)
                                {
                                    <div>
                                        <a asp-action="File" asp-route-id="@doc.Id">@doc.FileName</a> - @Html.DisplayFor(modelItem => doc.CreatedDate)
                                    </div>
                                }
                            </td>

                            <td class="text-right todelete">
                               
                                <a asp-action="PreView" asp-route-id="@item.Id" class="btn btn-light btn-sm">
                                    <i class="fa fa-eye"></i>
                                </a>
                                <a asp-action="Print" asp-route-id="@item.Id" target="_blank" class="btn btn-light btn-sm">
                                    <i class="fa fa-print"></i>
                                </a>
                                @if (isAdminOrManager)
                                {

                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-light btn-sm">
                                        <i class="fa fa-pen"></i>
                                    </a>
                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-light btn-sm">
                                        <i class="fa fa-trash-alt"></i>
                                    </a>

                                }
                            </td>
                        </tr>
                    }
                </tbody>
                <!--Table body-->
            </table>

            <!--Table-->
        </div>

    </div>

</div>

<!-- Table with panel -->
<br>
<br>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";

    var startIndex = Math.Max(Model.PageIndex - 5, 1);
    var finishIndex = Math.Min(Model.PageIndex + 5, Model.TotalPages);
}
<ul class="pagination">
    <li class="page-item @prevDisabled">
        <a asp-action="Index"
           asp-route-pageNumber="@(Model.PageIndex == startIndex)"
           asp-route-q="@ViewBag.SearchText"
           asp-route-dateFrom="@ViewBag.DateFrom"
           asp-route-dateFor="@ViewBag.DateFor"
           class="page-link">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
        </a>
    </li>
    <li class="page-item @prevDisabled">
        <a asp-action="Index"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-q="@ViewBag.SearchText"
           asp-route-dateFrom="@ViewBag.DateFrom"
           asp-route-dateFor="@ViewBag.DateFor"
           class="page-link">
            <span aria-hidden="true">&larr;</span>
            <span class="sr-only">Previous</span>
        </a>
    </li>

    @for (var j = startIndex; j <= finishIndex; j++)
    {
        var isActive = Model.PageIndex == j ? "active" : "";

        <li class="page-item @isActive">
            <a sp-action="Index"
               asp-route-pageNumber="@j"
               asp-route-q="@ViewBag.SearchText"
               asp-route-dateFrom="@ViewBag.DateFrom"
               asp-route-dateFor="@ViewBag.DateFor"
               class="page-link">
                @j
            </a>
        </li>
    }

    <li class="page-item @nextDisabled">
        <a asp-action="Index"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-q="@ViewBag.SearchText"
           asp-route-dateFrom="@ViewBag.DateFrom"
           asp-route-dateFor="@ViewBag.DateFor"
           class="page-link">
            <span aria-hidden="true">&rarr;</span>
            <span class="sr-only">Next</span>
        </a>
    </li>
    <li class="page-item @nextDisabled">
        <a asp-action="Index"
           asp-route-pageNumber="@(Model.PageIndex + (finishIndex - Model.PageIndex))"
           asp-route-q="@ViewBag.SearchText"
           asp-route-dateFrom="@ViewBag.DateFrom"
           asp-route-dateFor="@ViewBag.DateFor"
           class="page-link">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
        </a>
    </li>

</ul>

<asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
<!-- a ScriptManager is required when working with UpdatePanels -->

Views/Documents/PreView.cshtml
@model DocumentProcessing.ViewModels.DocumentListViewModel

@{
    ViewData["Title"] = "PreView";
}

<h1>Пешнамоиш</h1>
<hr>
<div class="container">
    <div class="card col-md-12">
        <br>
        <h4>Ҳуҷҷат</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Applicant)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Applicant)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EntryNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EntryNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Purpose)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Purpose)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Appointment)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Appointment)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Status)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Status)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Recipient)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Recipient)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.VisaId)
            </dt>
            <dd class="col-sm-10">
                @ViewBag.ReqId
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.VisaDateType)  
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.VisaDate)   @Html.DisplayFor(model => model.VisaDateType)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.VisaType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.VisaType)
            </dd>
            
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
    </div>
</div>