ViewModels/Roles/EditRoleViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace DocumentProcessing.ViewModels.Roles
{
    public class EditRoleViewModel
    {
        public string UserId { get; set; }

        public IEnumerable<IdentityRole> UserRoles { get; set; }
        
        public IEnumerable<IdentityRoleViewModel> Roles { get; set; }
    }
}

ViewModels/UsersViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace DocumentProcessing.ViewModels
{
    public class UsersViewModel
    {
        public string Id { get; set; }

        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [Display(Name = "Email confirmed")]
        public bool EmailConfirmed { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Roles")]
        public IEnumerable<IdentityRole> Roles { get; set; }

    }
}

Controllers/RoleController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DocumentProcessing.ViewModels.Roles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DocumentProcessing.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;

        public RoleController(RoleManager<IdentityRole> roleManager, IMapper mapper)
        {
            _roleManager = roleManager;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _roleManager.CreateAsync(_mapper.Map<RoleViewModel, IdentityRole>(model));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                AddErrors(result);
            }
            return View();
        }

        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            return View(_mapper.Map<IdentityRole, RoleViewModel>(role));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {

            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(model.Id);
                role.Name = model.Name;
                var result = await _roleManager.UpdateAsync(role);
                
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                AddErrors(result);
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            return View(role);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(IdentityRole model)
        {
            var result = await _roleManager.DeleteAsync(model);
            if (result.Succeeded)
                return RedirectToAction("Index");

            return View();

        }
        
        protected void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DocumentProcessing.Mappings;
using DocumentProcessing.Models;
using DocumentProcessing.ViewModels;
using DocumentProcessing.ViewModels.Roles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DocumentProcessing.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IUserRolesMapper _userRolesMapper;
        private readonly IMapper _mapper;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public UsersController(
            IUserRolesMapper userRolesMapper,
            IMapper mapper,
            RoleManager<IdentityRole> roleManager,
            UserManager<ApplicationUser> userManager)
        {
            _userRolesMapper = userRolesMapper;
            _mapper = mapper;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public ActionResult Index()
        {
            var users = _userManager.Users.ToList();
            IEnumerable<UsersViewModel> model = _mapper.Map<IEnumerable<ApplicationUser>, IEnumerable<UsersViewModel>>(users);
            return View(model);
        }

        public async Task<ActionResult> EditRole(string id = null, UsersMessageId? message = null)
        {
            ViewBag.StatusMessage =
                message == UsersMessageId.RoleAddedSuccess ? "Roles has been changed." : "";

            var model = await _userRolesMapper.GetEditRoleViewModel(id);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> EditRole(EditRoleViewModel model)
        {
            var result = await UpdateUserRoles(model);
            if (result.Succeeded)
            {
                return RedirectToAction("EditRole", new { id = model.UserId, message = UsersMessageId.RoleAddedSuccess });
            }
            AddErrors(result);
            return View(model);
        }
        

        public enum UsersMessageId
        {
            RoleAddedSuccess,
            Error
        }
        
        protected void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
        
        public async Task<IdentityResult> UpdateUserRoles(EditRoleViewModel model)
        {
            try
            {
                var selectedRoles = model.Roles.Where(ir => ir.IsSelected);
                var unSelectedRoles = model.Roles.Where(ir => !ir.IsSelected);

                var user = await _userManager.FindByIdAsync(model.UserId);
                var userRolesString = await _userManager.GetRolesAsync(user);

                var userRoles = userRolesString.Select(async x => await _roleManager.FindByNameAsync(x))
                    .Select(t => t.Result)
                    .Where(i => i != null)
                    .ToList();

                var rolesToAdd = selectedRoles.Where(r => !userRoles.Select(i => i.Id).Contains(r.Id));
                var rolesToRemove = unSelectedRoles.Where(r => userRoles.Select(ur => ur.Id).Contains(r.Id));

                if (rolesToAdd.Any())
                    await _userManager.AddToRolesAsync(user, rolesToAdd.Select(ir => ir.Name).ToArray());

                if (rolesToRemove.Any())
                    await _userManager.RemoveFromRolesAsync(user, rolesToRemove.Select(ir => ir.Name).ToArray());

                return IdentityResult.Success;
            }
            catch (Exception ex)
            {
                return IdentityResult.Failed(new IdentityError
                {
                    Description = ex.Message
                    
                });
            }
        }
    }
}

Views/Users/EditRole.cshtml
@using Microsoft.AspNetCore.Identity
@model DocumentProcessing.ViewModels.Roles.EditRoleViewModel

@{
    ViewBag.Title = "Edit role";
}

<h2>@ViewBag.Title</h2>
<h4>User roles and permissions</h4>

<p class="text-success">@ViewBag.StatusMessage</p>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.HiddenFor(m => m.UserId)

            <div class="col-md-10">
                <label>User Roles</label>
                @foreach (IdentityRole item in Model.UserRoles)
                {
                    <ul>
                        <li>
                           
                        </li>
                    </ul>
                }
            </div>
        </div>
        <hr />
        <p>
            @Html.ActionLink("Create New", "Create", "Role")
        </p>
        <div class="form-group">
            <div class="col-md-10">
                <label>Change roles</label>
                @Html.EditorFor(m => m.Roles)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Save" class="btn btn-primary btn-sm" style="min-width:200px" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Users/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<DocumentProcessing.ViewModels.UsersViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Last name
        </th>
        <th>
            Email
        </th>
        <th>
            Email confirmed
        </th>
        <th style="min-width: 200px">
            Roles
        </th>
        <th style="min-width: 200px">
            Permissions
        </th>
        <th>
            User name
        </th>       
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailConfirmed)
            </td>
            <td>
                @foreach(IdentityRole role in item.Roles)
                {
                    <p>@role.Name</p>
                }
            </td>

            <td>
                @Html.ActionLink("Edit", "EditRole", new { id = item.Id }) 
            </td>
        </tr>
    }

</table>